### ISSUE TITLE
workspace names

### ISSUE THREAD

**Issue by ghost** [fthx/workspaces-bar#16]
could you please elaborate a bit about how to change the names?
could not follow existing instructions

**Comment by null-git** [comment]
https://www.reddit.com/r/gnome/comments/6am7q7/how_to_change_workspace_names_in_gnome_3102/

**Comment by fthx** [comment]
We'll have soon a cool feature for that.
For now, you can use too the workspaces indicator options (official GS extension):
![image](https://user-images.githubusercontent.com/23138504/154059324-ad299707-9fd3-4a67-bb9d-323ec62550e3.png)
