### ISSUE TITLE
Last update broke the extension in pop os 20.04

### ISSUE THREAD

**Issue by tinuthomson** [fthx/workspaces-bar#2]

**Comment by fthx** [comment]
Well, that's a quite short bug report...
Do you have any error message in Logs (search sor string "fthx") ?
Do you have GNOME Shell extensions (official ones) package installed ?

**Comment by fthx** [comment]
So, I installed a Pop OS 20.04 virtual machine.

I installed the extension.
It works.

I verified that the gsettings schema exists.
It does.

I changed workspaces to names.
It works.

So I close this now. I do use Ubuntu 20.04 so it's close to your Pop OS 20.04.
Feel free to reopen if you can provide more infos.
