### ISSUE TITLE
Add Gnome 40 as supported version?

### ISSUE THREAD

**Issue by edgar-vincent** [fthx/workspaces-bar#3]
Hi!

I just upgraded to Gnome 40 on my Arch Linux install and this extension seems to work fine after having modified the `metadata.json` file. It might need more testing, but I just wanted to let you know.

EV

**Comment by fthx** [comment]
Ok thanks!
I've just uploaded the needed changes.
You'll soon have a new version through GS extensions updates. No noticeable changes.

**Comment by fthx** [comment]
Ok, I've just tested this one with my Fedora 34 VM and it seems ok.
There are some changes in GS 40's panel (background on elements hover) that needed to be checked first...

**Comment by edgar-vincent** [comment]
Thanks a lot!
