### ISSUE TITLE
Indicate if workspaces have active applications

### ISSUE THREAD

**Issue by null-git** [fthx/workspaces-bar#5]
First, thank you for this extension!

Would it be possible to add some simple indication whether workspaces are empty or have applications running on them?

Maybe only set the dark grey background color for workspaces that have apps running and have it transparent otherwise? This shouldn't change much for dynamic workspaces but would be very helpful for static workspaces.

**Comment by fthx** [comment]
https://github.com/fthx/workspaces-bar/commit/081ebc8c1ce60497278d405e71640cfeac76df3a

I close this now. Feel free to ask for styling changes if needed.
I tried to make it simple:
- border = active windows;
- grey background = active workspace.

**Comment by fthx** [comment]
This one is correct...
https://github.com/fthx/workspaces-bar/commit/b3383d1b19999db6635a615b61e6362aa4fc37b8

**Comment by null-git** [comment]
This is great. Thanks :)

**Comment by null-git** [comment]
I must say I preferred the icons without the borders. I played around with the CSS a bit and came up with this:
```
.desktop-label-nonempty-active {
  margin-left: 0px;
  margin-right: 8px;
  background-color: rgba(154, 154, 154, 0.7);
  border-radius: 4px;
}

.desktop-label-nonempty-inactive {
  margin-left: 0px;
  margin-right: 8px;
  background-color: rgba(96, 96, 96, 0.7);
  border-radius: 4px;
}

.desktop-label-empty-active {
  margin-left: 0px;
  margin-right: 8px;
  background-color: rgba(154, 154, 154, 0.7);
  border-radius: 4px;
}

.desktop-label-empty-inactive {
  margin-left: 0px;
  margin-right: 8px;
  background-color: rgba(0, 0, 0, 0.0);
  border-radius: 4px;
}
```

Just as a suggestion. What do you think?

**Comment by fthx** [comment]
Ok, I've changed this.
