### ISSUE TITLE
Hide empty workspaces

### ISSUE THREAD

**Issue by jestin-g** [fthx/workspaces-bar#7]
Hi,

First of all, thank you very much for this extension, it really looks amazing.

Do you think it is possible to add a feature that would hide the workspaces that are not used ?

**Comment by fthx** [comment]
Salut,

I don't understand what's the point here. The latest update introduces a windows watch by workspace. The empty (static) workspaces don't have a greyish background.
What version of GS do you use?

**Comment by jestin-g** [comment]
I am using Gnome 3.38 (Ubuntu 20.10)

I was thinking of something that would work the same way as i3, where the empty workspaces are not shown at all (If there is not window open on the workspace 5, the "5" is not displayed).

**Comment by fthx** [comment]
Ok, I checked the i3's way. I do use GS 3.38 (Debian 11).

I won't do that:
- this needs to draw frames to access hidden workspaces labels;
- some people don't like frames;
- some people do use names for static workspaces and want to keep them displayed;
- etc.

So, maybe I will make prefs for this extension, but I want at the moment to keep a just-work-way without that. I suggest you to play with css stylesheet, maybe with a `color: rgba(...);` equal to background's in empty-workspaces sections?

**Comment by fthx** [comment]
PS: did you try BaBar extension?

**Comment by null-git** [comment]
There's also https://extensions.gnome.org/extension/3968/improved-workspace-indicator/ which aims to be similar to i3.

**Comment by jestin-g** [comment]
@fthx I see your point, thanks for your answer !

@null-git I'll check that, thank you
