### ISSUE TITLE
Dropdown view?

### ISSUE THREAD

**Issue by v-marinkov** [fthx/workspaces-bar#8]
Hi, thanks for the nice extension!
I was wondering if there is a way to make the workspaces show as a dropdown instead of all at the same time. I like to separate my workspaces for particular tasks and don't want to be seeing the others (think "Free time", "Work", "Focus", etc.).

An example is this extension which was great but doesn't work with GNOME 40 and seems abandoned: https://github.com/Tomha/gnome-shell-extension-workspace-switcher

**Comment by fthx** [comment]
Sorry I just find I forgot this thread!
I won't do that: this extension has to stay simple, very basic.
I don't have the time, additionally! I work on Dock from Dash at the moment.
